/**
 * Content sample packs for CV Live Editor.
 * Each pack matches the draft content shape: fields, lists, photo, contactVisibility.
 * Loaded as a static sibling of index.html (window.CV_CONTENT_SAMPLES).
 */
(function (global) {
  "use strict";

  const VIS_ALL = {
    phone: true,
    email: true,
    address: true,
    linkedin: true,
    github: true,
  };
  const VIS_NO_GITHUB = {
    phone: true,
    email: true,
    address: true,
    linkedin: true,
    github: false,
  };

  /** @type {Array<{id: string, label: string, fields: object, lists: object, photo?: string, contactVisibility?: object}>} */
  const CV_CONTENT_SAMPLES = [
    {
      id: "software-mobile",
      label: "Software Engineer / Mobile Engineer",
      photo: "samples/photos/software-mobile.jpg",
      contactVisibility: { ...VIS_ALL },
      fields: {
        name: "Maya<br />Chen",
        title: "Senior Mobile Engineer",
        phone: "4155550198",
        phoneDial: "1",
        phoneCountry: "US",
        email: "maya.chen@example.com",
        address: "214 Market St., San Francisco, CA 94105",
        linkedin: "mayachen-mobile",
        github: "mayachen",
        about:
          "Mobile engineer focused on shipping reliable iOS and Android apps that feel fast and intentional. I care about clean architecture, thoughtful offline behavior, and collaboration between design and platform teams.",
      },
      lists: {
        skills: [
          {
            name: "Mobile",
            skills: ["Swift", "Kotlin", "Flutter", "React Native", "Jetpack Compose"],
          },
          {
            name: "Platform",
            skills: ["REST APIs", "GraphQL", "CI/CD", "Firebase", "App Store / Play Console"],
          },
        ],
        languages: ["English", "Mandarin"],
        education: [
          {
            title: "B.S. Computer Science",
            org: "University of Washington",
            location: "Seattle, WA",
            startYear: "2014",
            startMonth: "09",
            endYear: "2018",
            endMonth: "06",
            endPresent: false,
            desc: "Focused on human-computer interaction and distributed systems. Capstone built a cross-platform transit companion with offline maps.",
          },
        ],
        experience: [
          {
            title: "Senior Mobile Engineer",
            org: "Northwind Labs",
            location: "San Francisco, CA",
            startYear: "2022",
            startMonth: "03",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Led the consumer Android rewrite to Kotlin Multiplatform shared modules.\nCut cold-start time by 28% through lazy module loading.\nPartnered with design on a design-system token pipeline for mobile.",
            bullets: true,
          },
          {
            title: "Mobile Engineer",
            org: "Harbor Pay",
            location: "San Francisco, CA",
            startYear: "2019",
            startMonth: "07",
            endYear: "2022",
            endMonth: "02",
            endPresent: false,
            desc: "Owned iOS wallet flows and biometric auth. Shipped Face ID + PIN fallback used by 1.2M monthly actives. Mentored two junior engineers through their first production releases.",
            bullets: false,
          },
          {
            title: "Software Engineer Intern",
            org: "Cascade Softworks",
            location: "Seattle, WA",
            startYear: "2017",
            startMonth: "06",
            endYear: "2017",
            endMonth: "09",
            endPresent: false,
            desc: "Built Flutter prototypes for field-service reporting and contributed widget tests to the shared UI kit.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "PulseFit — Offline Workout Tracker",
            reference: "github.com/mayachen/pulsefit",
            referenceLink: true,
            year: "2024",
            desc: "Cross-platform fitness tracker with local-first sync, Apple Health / Health Connect bridges, and a custom charting layer.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Jordan Hale",
            role: "Northwind Labs / Engineering Manager",
            phone: "+1 415-555-0142",
            email: "jordan.hale@example.com",
          },
          {
            name: "Priya Natarajan",
            role: "Harbor Pay / Staff Engineer",
            phone: "+1 628-555-0177",
            email: "priya.n@example.com",
          },
        ],
      },
    },
    {
      id: "devops-platform",
      label: "DevOps / Platform Engineering",
      photo: "samples/photos/devops-platform.jpg",
      contactVisibility: { ...VIS_ALL },
      fields: {
        name: "Owen<br />Brooks",
        title: "Platform Engineer",
        phone: "7700900123",
        phoneDial: "44",
        phoneCountry: "GB",
        email: "owen.brooks@example.com",
        address: "88 Clerkenwell Rd., London EC1M 5RJ",
        linkedin: "owenbrooks-sre",
        github: "obrooks",
        about:
          "Platform engineer who builds the boring-but-critical path: reliable deploys, clear observability, and paved roads that product teams actually want to use. Happiest when incident noise goes down and developer confidence goes up.",
      },
      lists: {
        skills: [
          {
            name: "Infrastructure",
            skills: ["Kubernetes", "Terraform", "AWS", "Helm", "Argo CD"],
          },
          {
            name: "Reliability",
            skills: ["Prometheus", "Grafana", "OpenTelemetry", "Incident response", "SLOs"],
          },
        ],
        languages: ["English"],
        education: [
          {
            title: "M.Eng. Computing",
            org: "Imperial College London",
            location: "London, UK",
            startYear: "2013",
            startMonth: "10",
            endYear: "2017",
            endMonth: "07",
            endPresent: false,
            desc: "Systems and networking focus. Dissertation on automated capacity planning for container fleets.",
          },
        ],
        experience: [
          {
            title: "Platform Engineer",
            org: "Ledgerline",
            location: "London, UK",
            startYear: "2021",
            startMonth: "05",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Own the shared Kubernetes platform serving 40+ services.\nIntroduced progressive delivery with Argo Rollouts and automated rollback.\nCut mean time to recover from deploy regressions from 45m to under 12m.",
            bullets: true,
          },
          {
            title: "Site Reliability Engineer",
            org: "Brightstack",
            location: "Manchester, UK",
            startYear: "2018",
            startMonth: "02",
            endYear: "2021",
            endMonth: "04",
            endPresent: false,
            desc: "Ran on-call for payments edge services. Built Terraform modules for multi-account AWS networking and standardized logging pipelines into Loki.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Golden Path CLI",
            reference: "github.com/obrooks/golden-path",
            referenceLink: true,
            year: "2023",
            desc: "Internal-style starter that scaffolds service repos with CI, Helm chart, dashboards, and runbooks from one command.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Hannah Croft",
            role: "Ledgerline / Head of Platform",
            phone: "+44 20 7946 0123",
            email: "hannah.croft@example.com",
          },
          {
            name: "Marcus Adeyemi",
            role: "Brightstack / SRE Lead",
            phone: "+44 161 555 0190",
            email: "marcus.a@example.com",
          },
        ],
      },
    },
    {
      id: "ai-ml",
      label: "AI / Machine Learning",
      photo: "samples/photos/ai-ml.jpg",
      contactVisibility: { ...VIS_ALL },
      fields: {
        name: "Aisha<br />Rahman",
        title: "Machine Learning Engineer",
        phone: "4165550144",
        phoneDial: "1",
        phoneCountry: "CA",
        email: "aisha.rahman@example.com",
        address: "120 King St. W, Toronto, ON M5H 1A1",
        linkedin: "aisharahman-ml",
        github: "arahman-ml",
        about:
          "ML engineer bridging research prototypes and production systems. I specialize in ranking, evaluation rigor, and keeping models honest under real traffic—not just leaderboard scores.",
      },
      lists: {
        skills: [
          {
            name: "ML",
            skills: ["PyTorch", "scikit-learn", "Feature stores", "LLM fine-tuning", "A/B testing"],
          },
          {
            name: "Engineering",
            skills: ["Python", "Spark", "Airflow", "Docker", "FastAPI"],
          },
        ],
        languages: ["English", "Urdu", "French"],
        education: [
          {
            title: "M.Sc. Applied Computing",
            org: "University of Toronto",
            location: "Toronto, ON",
            startYear: "2017",
            startMonth: "09",
            endYear: "2019",
            endMonth: "04",
            endPresent: false,
            desc: "Concentration in machine learning. Thesis on calibration for multi-label classifiers in clinical NLP.",
          },
          {
            title: "B.Sc. Statistics",
            org: "McGill University",
            location: "Montreal, QC",
            startYear: "2013",
            startMonth: "09",
            endYear: "2017",
            endMonth: "05",
            endPresent: false,
            desc: "Honours statistics with computer science minor.",
          },
        ],
        experience: [
          {
            title: "Machine Learning Engineer",
            org: "Northstar Commerce",
            location: "Toronto, ON",
            startYear: "2021",
            startMonth: "08",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Own search ranking models for marketplace discovery.\nShipped a two-tower retrieval stack that lifted conversion 6.4%.\nBuilt evaluation harnesses that blocked silent quality regressions before release.",
            bullets: true,
          },
          {
            title: "Data Scientist",
            org: "Helix Health Analytics",
            location: "Toronto, ON",
            startYear: "2019",
            startMonth: "06",
            endYear: "2021",
            endMonth: "07",
            endPresent: false,
            desc: "Developed risk-scoring models for care coordination. Partnered with clinicians on feature definitions and fairness reviews.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "EvalKit for Ranking",
            reference: "github.com/arahman-ml/evalkit",
            referenceLink: true,
            year: "2024",
            desc: "Lightweight library for offline ranking metrics, slice analysis, and experiment report generation.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Daniel Cho",
            role: "Northstar Commerce / ML Director",
            phone: "+1 416-555-0188",
            email: "daniel.cho@example.com",
          },
          {
            name: "Dr. Elise Moreau",
            role: "Helix Health / Principal Scientist",
            phone: "+1 647-555-0112",
            email: "elise.moreau@example.com",
          },
        ],
      },
    },
    {
      id: "data-analytics",
      label: "Data / Analytics",
      photo: "samples/photos/data-analytics.jpg",
      contactVisibility: { ...VIS_ALL },
      fields: {
        name: "Noah<br />Patel",
        title: "Analytics Engineer",
        phone: "612345678",
        phoneDial: "61",
        phoneCountry: "AU",
        email: "noah.patel@example.com",
        address: "45 Collins St., Melbourne VIC 3000",
        linkedin: "noahpatel-data",
        github: "npatel-sql",
        about:
          "Analytics engineer who turns messy warehouse tables into trusted metrics. I like clear dbt models, documented definitions, and dashboards that answer the question before the meeting starts.",
      },
      lists: {
        skills: [
          {
            name: "Analytics",
            skills: ["SQL", "dbt", "Looker", "Metabase", "Experiment analysis"],
          },
          {
            name: "Data stack",
            skills: ["BigQuery", "Snowflake", "Python", "Airflow", "Fivetran"],
          },
        ],
        languages: ["English", "Gujarati"],
        education: [
          {
            title: "B.Com. Business Analytics",
            org: "University of Melbourne",
            location: "Melbourne, AU",
            startYear: "2015",
            startMonth: "02",
            endYear: "2018",
            endMonth: "11",
            endPresent: false,
            desc: "Majored in business analytics with electives in econometrics and information systems.",
          },
        ],
        experience: [
          {
            title: "Analytics Engineer",
            org: "Coastal Retail Group",
            location: "Melbourne, AU",
            startYear: "2022",
            startMonth: "01",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Own the core commerce mart in dbt on BigQuery.\nReduced conflicting revenue definitions from five variants to one certified metric.\nPartnered with finance on month-end reconciliation automation.",
            bullets: true,
          },
          {
            title: "Data Analyst",
            org: "Kinetic Media",
            location: "Sydney, AU",
            startYear: "2019",
            startMonth: "03",
            endYear: "2021",
            endMonth: "12",
            endPresent: false,
            desc: "Built campaign performance reporting and audience cohort analyses for brand clients. Introduced version-controlled SQL instead of spreadsheet exports.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Metric Dictionary Starter",
            reference: "github.com/npatel-sql/metric-dictionary",
            referenceLink: true,
            year: "2023",
            desc: "Template repo for documenting certified metrics with owners, grain, and example queries.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Sophie Lang",
            role: "Coastal Retail / Head of Data",
            phone: "+61 3 5550 2211",
            email: "sophie.lang@example.com",
          },
          {
            name: "Ben Okonkwo",
            role: "Kinetic Media / Analytics Lead",
            phone: "+61 2 5550 3344",
            email: "ben.okonkwo@example.com",
          },
        ],
      },
    },
    {
      id: "product-design-ux",
      label: "Product Design / UX",
      photo: "samples/photos/product-design-ux.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Elena<br />Vargas",
        title: "Senior Product Designer",
        phone: "612345678",
        phoneDial: "31",
        phoneCountry: "NL",
        email: "elena.vargas@example.com",
        address: "Prinsengracht 263, 1016 GV Amsterdam",
        linkedin: "elenavargas-design",
        github: "",
        about:
          "Product designer who pairs research with crisp interaction design. I ship systems that scale, prototypes that persuade, and interfaces that stay calm under complexity.",
      },
      lists: {
        skills: [
          {
            name: "Design",
            skills: ["Figma", "Design systems", "Prototyping", "User research", "Accessibility"],
          },
          {
            name: "Collaboration",
            skills: ["Workshops", "Journey mapping", "Handoff", "Usability testing"],
          },
        ],
        languages: ["English", "Spanish", "Dutch"],
        education: [
          {
            title: "M.A. Interaction Design",
            org: "Design Academy Eindhoven",
            location: "Eindhoven, NL",
            startYear: "2016",
            startMonth: "09",
            endYear: "2018",
            endMonth: "07",
            endPresent: false,
            desc: "Studio work on civic services and multi-device interaction patterns.",
          },
        ],
        experience: [
          {
            title: "Senior Product Designer",
            org: "Orbit Finance",
            location: "Amsterdam, NL",
            startYear: "2021",
            startMonth: "04",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Lead designer for SME banking onboarding.\nCut average account-open time from 18 to 9 minutes.\nGrew the shared component library to 60+ accessible primitives.",
            bullets: true,
          },
          {
            title: "Product Designer",
            org: "Bluebird Apps",
            location: "Rotterdam, NL",
            startYear: "2018",
            startMonth: "09",
            endYear: "2021",
            endMonth: "03",
            endPresent: false,
            desc: "Designed B2B scheduling tools end-to-end. Ran quarterly research sprints and translated findings into prioritized opportunity maps.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Orbit Design System",
            reference: "orbit.example/design",
            referenceLink: true,
            year: "2024",
            desc: "Multi-brand token system with documentation site, Figma library, and WCAG AA checklist for every pattern.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Tom Bakker",
            role: "Orbit Finance / Design Director",
            phone: "+31 20 555 0191",
            email: "tom.bakker@example.com",
          },
          {
            name: "Inés Romero",
            role: "Bluebird Apps / Head of Product",
            phone: "+31 10 555 0288",
            email: "ines.romero@example.com",
          },
        ],
      },
    },
    {
      id: "marketing-brand",
      label: "Marketing / Brand",
      photo: "samples/photos/marketing-brand.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Lorna<br />Alvarado",
        title: "Marketing Manager",
        phone: "81234567890",
        phoneDial: "62",
        phoneCountry: "ID",
        email: "lorna.alvarado@example.com",
        address: "123 Anywhere St., Any City, ST 12345",
        linkedin: "lornaalvarado",
        github: "",
        about:
          "Brand and growth marketer who connects storytelling with measurable campaigns. I build launch narratives, keep channels coherent, and translate performance data into sharper creative briefs.",
      },
      lists: {
        skills: [
          {
            name: "Marketing",
            skills: [
              "Brand strategy",
              "Campaign planning",
              "Content marketing",
              "Email lifecycle",
              "Social media",
            ],
          },
          {
            name: "Tools",
            skills: ["HubSpot", "Google Analytics", "Canva", "Notion", "A/B testing"],
          },
        ],
        languages: ["English", "Spanish", "French"],
        education: [
          {
            title: "Bachelor of Business Management",
            org: "Borcelle University",
            location: "Any City, ST",
            startYear: "2016",
            startMonth: "",
            endYear: "2020",
            endMonth: "",
            endPresent: false,
            desc: "Concentration in marketing and organizational leadership. Led the student brand club’s annual charity campaign.",
          },
        ],
        experience: [
          {
            title: "Marketing Manager",
            org: "Arowwai Industries",
            location: "Any City, ST",
            startYear: "2021",
            startMonth: "01",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Own integrated campaigns across web, email, and social.\nGrew qualified pipeline 32% year over year.\nRebuilt brand messaging guidelines adopted company-wide.",
            bullets: true,
          },
          {
            title: "Brand Specialist",
            org: "Arowwai Industries",
            location: "Any City, ST",
            startYear: "2019",
            startMonth: "06",
            endYear: "2020",
            endMonth: "12",
            endPresent: false,
            desc: "Supported product launches with landing pages, partner kits, and event storytelling. Coordinated freelance creatives and agencies.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Brand Campaign Hub",
            reference: "reallygreatsite.com/brand-hub",
            referenceLink: true,
            year: "2023",
            desc: "Centralized campaign assets, messaging pillars, and performance dashboards for a multi-market launch.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Harumi Kobayashi",
            role: "Wardiere Inc. / CEO",
            phone: "123-456-7890",
            email: "hello@reallygreatsite.com",
          },
          {
            name: "Bailey Dupont",
            role: "Wardiere Inc. / Marketing Director",
            phone: "123-456-7890",
            email: "hello@reallygreatsite.com",
          },
        ],
      },
    },
    {
      id: "sales-bd",
      label: "Sales / Business Development",
      photo: "samples/photos/sales-bd.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Marcus<br />Whitfield",
        title: "Enterprise Account Executive",
        phone: "3125550167",
        phoneDial: "1",
        phoneCountry: "US",
        email: "marcus.whitfield@example.com",
        address: "233 S Wacker Dr., Chicago, IL 60606",
        linkedin: "marcuswhitfield",
        github: "",
        about:
          "Enterprise AE who builds multi-threaded deals with clarity and patience. Strong on discovery, executive storytelling, and closing complex SaaS cycles without overselling the product.",
      },
      lists: {
        skills: [
          {
            name: "Sales",
            skills: [
              "Enterprise sales",
              "MEDDIC",
              "Negotiation",
              "Pipeline management",
              "Executive briefings",
            ],
          },
          {
            name: "Tools",
            skills: ["Salesforce", "Gong", "Outreach", "LinkedIn Sales Navigator"],
          },
        ],
        languages: ["English"],
        education: [
          {
            title: "B.A. Communications",
            org: "Northwestern University",
            location: "Evanston, IL",
            startYear: "2012",
            startMonth: "09",
            endYear: "2016",
            endMonth: "06",
            endPresent: false,
            desc: "Rhetoric and organizational communication. Captain of the debate team.",
          },
        ],
        experience: [
          {
            title: "Enterprise Account Executive",
            org: "Clearpath Software",
            location: "Chicago, IL",
            startYear: "2020",
            startMonth: "09",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Manage a $2.4M ARR book across Midwestern enterprise accounts.\nClosed three seven-figure expansions in FY25.\nConsistently ranked in top 10% of the Americas AE team.",
            bullets: true,
          },
          {
            title: "Business Development Manager",
            org: "Summit Cloud",
            location: "Chicago, IL",
            startYear: "2017",
            startMonth: "04",
            endYear: "2020",
            endMonth: "08",
            endPresent: false,
            desc: "Built mid-market pipeline from cold outbound and partner channels. Created a repeatable mutual action plan template still used by the team.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Vertical Playbook — Manufacturing",
            reference: "",
            referenceLink: false,
            year: "2024",
            desc: "Internal sales playbook covering persona maps, objection handling, and ROI models for plant operations buyers.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Rachel Kim",
            role: "Clearpath Software / VP Sales",
            phone: "+1 312-555-0109",
            email: "rachel.kim@example.com",
          },
          {
            name: "Andre Solomon",
            role: "Summit Cloud / Regional Director",
            phone: "+1 773-555-0145",
            email: "andre.solomon@example.com",
          },
        ],
      },
    },
    {
      id: "customer-success",
      label: "Customer Success / Support",
      photo: "samples/photos/customer-success.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Sofia<br />Martinez",
        title: "Customer Success Manager",
        phone: "5551234567",
        phoneDial: "52",
        phoneCountry: "MX",
        email: "sofia.martinez@example.com",
        address: "Av. Reforma 222, Ciudad de México, CDMX",
        linkedin: "sofiamartinez-cs",
        github: "",
        about:
          "Customer success lead focused on adoption, renewals, and turning feedback into product fuel. I build trusted relationships and clear health scores—not surprise churn calls.",
      },
      lists: {
        skills: [
          {
            name: "Customer success",
            skills: [
              "Onboarding",
              "Renewals",
              "QBR facilitation",
              "Health scoring",
              "Escalation management",
            ],
          },
          {
            name: "Tools",
            skills: ["Gainsight", "Zendesk", "Intercom", "Salesforce", "Looker"],
          },
        ],
        languages: ["Spanish", "English"],
        education: [
          {
            title: "Licenciatura en Administración",
            org: "ITAM",
            location: "Mexico City, MX",
            startYear: "2014",
            startMonth: "08",
            endYear: "2018",
            endMonth: "06",
            endPresent: false,
            desc: "Business administration with a minor in information technology management.",
          },
        ],
        experience: [
          {
            title: "Customer Success Manager",
            org: "NubeOps",
            location: "Mexico City, MX",
            startYear: "2021",
            startMonth: "02",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Own a portfolio of 45 mid-market SaaS accounts.\nMaintained 97% net retention across two renewals cycles.\nLaunched a structured onboarding playbook that cut time-to-value by 3 weeks.",
            bullets: true,
          },
          {
            title: "Support Team Lead",
            org: "Parcelito",
            location: "Guadalajara, MX",
            startYear: "2018",
            startMonth: "07",
            endYear: "2021",
            endMonth: "01",
            endPresent: false,
            desc: "Led an 8-person support pod for a logistics SaaS. Improved first-response SLA from 6h to under 90 minutes.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Customer Health Rubric",
            reference: "",
            referenceLink: false,
            year: "2023",
            desc: "Cross-functional health model combining product usage, support load, and executive engagement signals.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Luis Ortega",
            role: "NubeOps / Head of CS",
            phone: "+52 55 5555 0199",
            email: "luis.ortega@example.com",
          },
          {
            name: "Camila Ruiz",
            role: "Parcelito / COO",
            phone: "+52 33 5555 0271",
            email: "camila.ruiz@example.com",
          },
        ],
      },
    },
    {
      id: "pr-comms",
      label: "Public Relations / Communications",
      photo: "samples/photos/pr-comms.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Claire<br />Nguyen",
        title: "Communications Manager",
        phone: "2125550183",
        phoneDial: "1",
        phoneCountry: "US",
        email: "claire.nguyen@example.com",
        address: "75 Varick St., New York, NY 10013",
        linkedin: "clairenguyen-comms",
        github: "",
        about:
          "Communications manager who crafts crisp narratives for press, executives, and employees. Calm under deadline pressure and fluent in both media relations and internal storytelling.",
      },
      lists: {
        skills: [
          {
            name: "Communications",
            skills: [
              "Media relations",
              "Crisis communications",
              "Executive ghostwriting",
              "Press strategy",
              "Internal comms",
            ],
          },
          {
            name: "Tools",
            skills: ["Muck Rack", "Cision", "Notion", "Canva", "Google Workspace"],
          },
        ],
        languages: ["English", "Vietnamese"],
        education: [
          {
            title: "B.A. Journalism",
            org: "Columbia University",
            location: "New York, NY",
            startYear: "2013",
            startMonth: "09",
            endYear: "2017",
            endMonth: "05",
            endPresent: false,
            desc: "Print and digital journalism with a concentration in political reporting.",
          },
        ],
        experience: [
          {
            title: "Communications Manager",
            org: "Lumen & Co.",
            location: "New York, NY",
            startYear: "2021",
            startMonth: "06",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Lead external communications for a climate-tech portfolio company.\nSecured placements in FT, Wired, and TechCrunch for Series C narrative.\nBuilt a rapid-response desk for product and regulatory announcements.",
            bullets: true,
          },
          {
            title: "Public Relations Associate",
            org: "Harbor PR",
            location: "New York, NY",
            startYear: "2017",
            startMonth: "08",
            endYear: "2021",
            endMonth: "05",
            endPresent: false,
            desc: "Supported consumer and tech clients with pitch calendars, media lists, and event press rooms.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Series C Narrative Kit",
            reference: "",
            referenceLink: false,
            year: "2024",
            desc: "Full messaging architecture, FAQ, and embargoed brief pack used across investor and press channels.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Helen Park",
            role: "Lumen & Co. / VP Communications",
            phone: "+1 212-555-0140",
            email: "helen.park@example.com",
          },
          {
            name: "Greg Alvarez",
            role: "Harbor PR / Managing Director",
            phone: "+1 646-555-0196",
            email: "greg.alvarez@example.com",
          },
        ],
      },
    },
    {
      id: "ops-pm",
      label: "Operations / Project Management",
      photo: "samples/photos/ops-pm.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Jonas<br />Keller",
        title: "Senior Project Manager",
        phone: "301234567",
        phoneDial: "49",
        phoneCountry: "DE",
        email: "jonas.keller@example.com",
        address: "Friedrichstraße 123, 10117 Berlin",
        linkedin: "jonaskeller-pm",
        github: "",
        about:
          "Project manager who keeps cross-functional work visible, sequenced, and honest about risk. I specialize in delivery for product and operations programs without drowning teams in process.",
      },
      lists: {
        skills: [
          {
            name: "Delivery",
            skills: [
              "Agile facilitation",
              "Risk management",
              "Roadmapping",
              "Stakeholder updates",
              "Budget tracking",
            ],
          },
          {
            name: "Tools",
            skills: ["Jira", "Asana", "Confluence", "Miro", "Excel"],
          },
        ],
        languages: ["German", "English"],
        education: [
          {
            title: "M.Sc. Industrial Engineering",
            org: "TU Berlin",
            location: "Berlin, DE",
            startYear: "2014",
            startMonth: "10",
            endYear: "2017",
            endMonth: "03",
            endPresent: false,
            desc: "Focus on operations research and project systems.",
          },
        ],
        experience: [
          {
            title: "Senior Project Manager",
            org: "Feldhaus Digital",
            location: "Berlin, DE",
            startYear: "2020",
            startMonth: "11",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Run concurrent product launches across engineering, marketing, and support.\nDelivered a multi-market checkout redesign three weeks ahead of plan.\nIntroduced lightweight RAID logs that leadership actually reads.",
            bullets: true,
          },
          {
            title: "Operations Coordinator",
            org: "Rhein Logistics",
            location: "Cologne, DE",
            startYear: "2017",
            startMonth: "05",
            endYear: "2020",
            endMonth: "10",
            endPresent: false,
            desc: "Coordinated warehouse process improvements and vendor onboarding timelines across three sites.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Launch Control Board",
            reference: "",
            referenceLink: false,
            year: "2023",
            desc: "Shared program board with dependency tracking, go/no-go criteria, and weekly executive digest automation.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Anke Vogt",
            role: "Feldhaus Digital / Director of PMO",
            phone: "+49 30 5555 0182",
            email: "anke.vogt@example.com",
          },
          {
            name: "Lars Hoffmann",
            role: "Rhein Logistics / Operations Lead",
            phone: "+49 221 5555 0240",
            email: "lars.hoffmann@example.com",
          },
        ],
      },
    },
    {
      id: "finance-accounting",
      label: "Finance / Accounting",
      photo: "samples/photos/finance-accounting.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Amelia<br />Foster",
        title: "Senior Financial Analyst",
        phone: "2079460958",
        phoneDial: "44",
        phoneCountry: "GB",
        email: "amelia.foster@example.com",
        address: "1 Canada Square, London E14 5AB",
        linkedin: "ameliafoster-fpna",
        github: "",
        about:
          "FP&A analyst who pairs clean models with clear narrative. I help leadership see trade-offs early—forecasts, variance stories, and investment cases that stand up in the board pack.",
      },
      lists: {
        skills: [
          {
            name: "Finance",
            skills: [
              "Financial modeling",
              "Forecasting",
              "Variance analysis",
              "Budgeting",
              "Board reporting",
            ],
          },
          {
            name: "Tools",
            skills: ["Excel", "SQL", "Adaptive Insights", "Power BI", "NetSuite"],
          },
        ],
        languages: ["English"],
        education: [
          {
            title: "ACA — Associate Chartered Accountant",
            org: "ICAEW",
            location: "London, UK",
            startYear: "2016",
            startMonth: "",
            endYear: "2019",
            endMonth: "",
            endPresent: false,
            desc: "Completed ACA while working in audit. Electives in financial management.",
          },
          {
            title: "B.Sc. Accounting & Finance",
            org: "University of Bath",
            location: "Bath, UK",
            startYear: "2012",
            startMonth: "10",
            endYear: "2015",
            endMonth: "07",
            endPresent: false,
            desc: "First-class honours. Dissertation on working-capital cycles in retail.",
          },
        ],
        experience: [
          {
            title: "Senior Financial Analyst",
            org: "Northbridge Retail",
            location: "London, UK",
            startYear: "2021",
            startMonth: "03",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Own monthly forecast and quarterly board pack for UK & Ireland.\nBuilt driver-based models that reduced forecast error by 18%.\nPartner with commercial teams on promotional ROI reviews.",
            bullets: true,
          },
          {
            title: "Audit Senior",
            org: "Hartley & Co.",
            location: "London, UK",
            startYear: "2016",
            startMonth: "09",
            endYear: "2021",
            endMonth: "02",
            endPresent: false,
            desc: "Led audits for mid-market retail and consumer clients. Coached juniors on substantive testing and clear workpapers.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Promo ROI Model",
            reference: "",
            referenceLink: false,
            year: "2024",
            desc: "Reusable workbook linking uplift, margin, and inventory risk for seasonal campaigns.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "James Whitaker",
            role: "Northbridge Retail / FP&A Director",
            phone: "+44 20 7946 0110",
            email: "james.whitaker@example.com",
          },
          {
            name: "Olivia Grant",
            role: "Hartley & Co. / Audit Partner",
            phone: "+44 20 7946 0225",
            email: "olivia.grant@example.com",
          },
        ],
      },
    },
    {
      id: "hr-people-ops",
      label: "Human Resource / People Ops",
      photo: "samples/photos/hr-people-ops.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Priya<br />Desai",
        title: "People Operations Lead",
        phone: "9876543210",
        phoneDial: "91",
        phoneCountry: "IN",
        email: "priya.desai@example.com",
        address: "14 Residency Rd., Bengaluru, KA 560025",
        linkedin: "priyadesai-people",
        github: "",
        about:
          "People ops lead who designs practical HR systems—hiring loops, onboarding, and performance rituals that scale without losing the human tone. Strong bias for clarity and fairness.",
      },
      lists: {
        skills: [
          {
            name: "People ops",
            skills: [
              "Recruiting operations",
              "Onboarding",
              "Performance cycles",
              "Compensation banding",
              "Employee relations",
            ],
          },
          {
            name: "Tools",
            skills: ["BambooHR", "Greenhouse", "Notion", "Slack", "Google Workspace"],
          },
        ],
        languages: ["English", "Hindi", "Kannada"],
        education: [
          {
            title: "MBA — Human Resources",
            org: "XLRI Jamshedpur",
            location: "Jamshedpur, IN",
            startYear: "2015",
            startMonth: "06",
            endYear: "2017",
            endMonth: "03",
            endPresent: false,
            desc: "HR specialization with coursework in organizational behavior and labour law.",
          },
        ],
        experience: [
          {
            title: "People Operations Lead",
            org: "Saffron Labs",
            location: "Bengaluru, IN",
            startYear: "2021",
            startMonth: "01",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Scale people systems from 80 to 220 employees.\nRedesigned onboarding to a 30-60-90 program with manager checklists.\nRan calibration workshops that improved rating distribution fairness.",
            bullets: true,
          },
          {
            title: "HR Business Partner",
            org: "Lotus Payments",
            location: "Hyderabad, IN",
            startYear: "2017",
            startMonth: "08",
            endYear: "2020",
            endMonth: "12",
            endPresent: false,
            desc: "Partnered with engineering and product orgs on hiring plans, employee relations, and policy updates.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Career Framework v2",
            reference: "",
            referenceLink: false,
            year: "2023",
            desc: "Level definitions, promotion criteria, and example behaviors for IC and manager tracks.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Ananya Iyer",
            role: "Saffron Labs / Head of People",
            phone: "+91 80 5555 0133",
            email: "ananya.iyer@example.com",
          },
          {
            name: "Rohan Mehta",
            role: "Lotus Payments / VP Engineering",
            phone: "+91 40 5555 0277",
            email: "rohan.mehta@example.com",
          },
        ],
      },
    },
    {
      id: "legal-compliance",
      label: "Legal / Compliance",
      photo: "samples/photos/legal-compliance.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Daniel<br />Okoro",
        title: "Compliance Counsel",
        phone: "2025550144",
        phoneDial: "1",
        phoneCountry: "US",
        email: "daniel.okoro@example.com",
        address: "1001 Pennsylvania Ave. NW, Washington, DC 20004",
        linkedin: "danielokoro-law",
        github: "",
        about:
          "Compliance counsel who translates regulation into workable controls. I partner with product and security to keep growth ambitious and documentation audit-ready.",
      },
      lists: {
        skills: [
          {
            name: "Legal & compliance",
            skills: [
              "Regulatory analysis",
              "Policy drafting",
              "Vendor due diligence",
              "Privacy (GDPR/CCPA)",
              "Contract review",
            ],
          },
          {
            name: "Domains",
            skills: ["Fintech", "SaaS", "Cross-border data", "AML basics"],
          },
        ],
        languages: ["English", "Igbo"],
        education: [
          {
            title: "J.D.",
            org: "Georgetown University Law Center",
            location: "Washington, DC",
            startYear: "2014",
            startMonth: "08",
            endYear: "2017",
            endMonth: "05",
            endPresent: false,
            desc: "Focus on administrative law and technology policy. Editor, Journal of Law & Technology.",
          },
          {
            title: "B.A. Political Science",
            org: "Howard University",
            location: "Washington, DC",
            startYear: "2010",
            startMonth: "08",
            endYear: "2014",
            endMonth: "05",
            endPresent: false,
            desc: "Magna cum laude. Thesis on regulatory agencies and digital markets.",
          },
        ],
        experience: [
          {
            title: "Compliance Counsel",
            org: "Fairledger",
            location: "Washington, DC",
            startYear: "2021",
            startMonth: "07",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Advise product teams on consumer finance and privacy requirements.\nBuilt a control inventory mapped to SOC 2 and GDPR articles.\nLed responses for two regulatory examinations with no material findings.",
            bullets: true,
          },
          {
            title: "Associate Attorney",
            org: "Reed & Hale LLP",
            location: "Washington, DC",
            startYear: "2017",
            startMonth: "09",
            endYear: "2021",
            endMonth: "06",
            endPresent: false,
            desc: "Supported financial services clients on compliance programs, investigations, and policy updates.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Privacy Impact Assessment Playbook",
            reference: "",
            referenceLink: false,
            year: "2024",
            desc: "Reusable PIA template and decision tree for new data processing features.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Sarah Lindstrom",
            role: "Fairledger / General Counsel",
            phone: "+1 202-555-0171",
            email: "sarah.lindstrom@example.com",
          },
          {
            name: "Michael Reed",
            role: "Reed & Hale LLP / Partner",
            phone: "+1 202-555-0284",
            email: "michael.reed@example.com",
          },
        ],
      },
    },
    {
      id: "real-estate",
      label: "Real Estate / Property",
      photo: "samples/photos/real-estate.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Harper<br />Quinn",
        title: "Commercial Property Manager",
        phone: "6045550192",
        phoneDial: "1",
        phoneCountry: "CA",
        email: "harper.quinn@example.com",
        address: "555 Burrard St., Vancouver, BC V7X 1M8",
        linkedin: "harperquinn-re",
        github: "",
        about:
          "Property manager focused on tenant experience, operational reliability, and asset performance. Comfortable coordinating vendors, budgets, and capital projects across mixed-use buildings.",
      },
      lists: {
        skills: [
          {
            name: "Property",
            skills: [
              "Lease administration",
              "Tenant relations",
              "CapEx planning",
              "Vendor management",
              "Inspections",
            ],
          },
          {
            name: "Tools",
            skills: ["Yardi", "AppFolio", "Excel", "BuildingLink"],
          },
        ],
        languages: ["English", "French"],
        education: [
          {
            title: "Diploma — Real Property Management",
            org: "BCIT",
            location: "Burnaby, BC",
            startYear: "2014",
            startMonth: "09",
            endYear: "2016",
            endMonth: "05",
            endPresent: false,
            desc: "Coursework in commercial leasing, building systems, and strata governance.",
          },
        ],
        experience: [
          {
            title: "Commercial Property Manager",
            org: "Pacific Crest Realty",
            location: "Vancouver, BC",
            startYear: "2020",
            startMonth: "02",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Manage a 420k sq ft mixed-use portfolio.\nImproved tenant satisfaction scores by 14 points in two years.\nDelivered lobby and HVAC upgrades on time and under budget.",
            bullets: true,
          },
          {
            title: "Assistant Property Manager",
            org: "Harbourview Properties",
            location: "Vancouver, BC",
            startYear: "2016",
            startMonth: "07",
            endYear: "2020",
            endMonth: "01",
            endPresent: false,
            desc: "Supported residential and retail assets with renewals, maintenance coordination, and monthly owner reports.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Lobby Modernization — Granville Tower",
            reference: "",
            referenceLink: false,
            year: "2023",
            desc: "End-to-end coordination of design, tendering, and construction for a common-area refresh.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Diane Mercer",
            role: "Pacific Crest Realty / Director of Assets",
            phone: "+1 604-555-0138",
            email: "diane.mercer@example.com",
          },
          {
            name: "Chris Langford",
            role: "Harbourview Properties / Regional Manager",
            phone: "+1 778-555-0260",
            email: "chris.langford@example.com",
          },
        ],
      },
    },
    {
      id: "supply-chain",
      label: "Supply Chain / Logistics",
      photo: "samples/photos/supply-chain.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Kenji<br />Sato",
        title: "Supply Chain Manager",
        phone: "9012345678",
        phoneDial: "81",
        phoneCountry: "JP",
        email: "kenji.sato@example.com",
        address: "2-5-1 Nihonbashi, Chuo-ku, Tokyo 103-0027",
        linkedin: "kenjisato-scm",
        github: "",
        about:
          "Supply chain manager obsessed with flow: inventory health, carrier performance, and exception handling that protects service levels without inflating cost.",
      },
      lists: {
        skills: [
          {
            name: "Supply chain",
            skills: [
              "Demand planning",
              "Inventory optimization",
              "3PL management",
              "Inbound logistics",
              "S&OP",
            ],
          },
          {
            name: "Tools",
            skills: ["SAP", "Excel", "Power BI", "TMS", "WMS"],
          },
        ],
        languages: ["Japanese", "English"],
        education: [
          {
            title: "B.Eng. Industrial Engineering",
            org: "Keio University",
            location: "Tokyo, JP",
            startYear: "2011",
            startMonth: "04",
            endYear: "2015",
            endMonth: "03",
            endPresent: false,
            desc: "Studied operations research and production systems.",
          },
        ],
        experience: [
          {
            title: "Supply Chain Manager",
            org: "Hikari Consumer Goods",
            location: "Tokyo, JP",
            startYear: "2020",
            startMonth: "04",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Own planning for three product families across APAC.\nCut stockouts 22% while reducing average inventory days by 9.\nRenegotiated 3PL SLAs with clearer exception playbooks.",
            bullets: true,
          },
          {
            title: "Logistics Analyst",
            org: "Nippon Parcel Network",
            location: "Osaka, JP",
            startYear: "2015",
            startMonth: "04",
            endYear: "2020",
            endMonth: "03",
            endPresent: false,
            desc: "Analyzed lane performance and seasonal capacity. Supported warehouse slotting projects that improved pick rates.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "S&OP Cadence Redesign",
            reference: "",
            referenceLink: false,
            year: "2023",
            desc: "Monthly planning rhythm linking demand, supply, and finance with a single source-of-truth workbook.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Yuki Tanaka",
            role: "Hikari Consumer Goods / VP Supply Chain",
            phone: "+81 3-5555-0190",
            email: "yuki.tanaka@example.com",
          },
          {
            name: "Hiroshi Mori",
            role: "Nippon Parcel Network / Operations Manager",
            phone: "+81 6-5555-0244",
            email: "hiroshi.mori@example.com",
          },
        ],
      },
    },
    {
      id: "maritime-shipping",
      label: "Maritime / Shipping Operations",
      photo: "samples/photos/maritime-shipping.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Erik<br />Nilsen",
        title: "Shipping Operations Coordinator",
        phone: "91234567",
        phoneDial: "47",
        phoneCountry: "NO",
        email: "erik.nilsen@example.com",
        address: "Bryggen 12, 5003 Bergen",
        linkedin: "eriknilsen-maritime",
        github: "",
        about:
          "Maritime operations coordinator keeping vessels, agents, and cargo documentation aligned. Strong on port calls, charter party follow-through, and calm exception handling when weather or berths shift.",
      },
      lists: {
        skills: [
          {
            name: "Maritime ops",
            skills: [
              "Port call coordination",
              "Chartering support",
              "Cargo docs",
              "ISPS awareness",
              "Vendor liaison",
            ],
          },
          {
            name: "Tools",
            skills: ["IMOS", "Excel", "Email ops queues", "AIS tools"],
          },
        ],
        languages: ["Norwegian", "English", "German"],
        education: [
          {
            title: "B.Sc. Shipping Management",
            org: "Western Norway University of Applied Sciences",
            location: "Haugesund, NO",
            startYear: "2014",
            startMonth: "08",
            endYear: "2017",
            endMonth: "06",
            endPresent: false,
            desc: "Courses in maritime economics, logistics, and safety management.",
          },
        ],
        experience: [
          {
            title: "Shipping Operations Coordinator",
            org: "Fjordline Shipping",
            location: "Bergen, NO",
            startYear: "2020",
            startMonth: "01",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Coordinate dry-bulk port calls across Northern Europe.\nReduced average demurrage disputes through tighter SOF and NOR tracking.\nAct as primary shore contact during weather reroutes.",
            bullets: true,
          },
          {
            title: "Port Agency Assistant",
            org: "Nordic Port Services",
            location: "Stavanger, NO",
            startYear: "2017",
            startMonth: "08",
            endYear: "2019",
            endMonth: "12",
            endPresent: false,
            desc: "Supported vessel husbandry, crew changes, and customs documentation for offshore and cargo traffic.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Port Call Checklist Automation",
            reference: "",
            referenceLink: false,
            year: "2023",
            desc: "Shared checklist and status board for agents, ops, and masters covering pre-arrival through departure.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Ingrid Berg",
            role: "Fjordline Shipping / Operations Manager",
            phone: "+47 55 55 01 20",
            email: "ingrid.berg@example.com",
          },
          {
            name: "Paul Hagen",
            role: "Nordic Port Services / Agency Lead",
            phone: "+47 51 55 02 44",
            email: "paul.hagen@example.com",
          },
        ],
      },
    },
    {
      id: "agriculture",
      label: "Agriculture / Agribusiness",
      photo: "samples/photos/agriculture.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Lucia<br />Fernandez",
        title: "Agribusiness Operations Lead",
        phone: "911234567",
        phoneDial: "54",
        phoneCountry: "AR",
        email: "lucia.fernandez@example.com",
        address: "Av. Corrientes 1234, C1043 CABA, Buenos Aires",
        linkedin: "luciafernandez-agri",
        github: "",
        about:
          "Agribusiness operator connecting field reality with commercial plans. Experience in crop planning, co-op relations, and export-ready quality programs for specialty produce.",
      },
      lists: {
        skills: [
          {
            name: "Agribusiness",
            skills: [
              "Crop planning",
              "Supplier development",
              "Quality programs",
              "Export logistics",
              "Co-op relations",
            ],
          },
          {
            name: "Tools",
            skills: ["Excel", "FarmERP", "GPS field tools", "Power BI"],
          },
        ],
        languages: ["Spanish", "English", "Portuguese"],
        education: [
          {
            title: "Ingeniería Agronómica",
            org: "Universidad de Buenos Aires",
            location: "Buenos Aires, AR",
            startYear: "2011",
            startMonth: "03",
            endYear: "2016",
            endMonth: "12",
            endPresent: false,
            desc: "Focus on production systems and agricultural economics.",
          },
        ],
        experience: [
          {
            title: "Agribusiness Operations Lead",
            org: "Pampa Fresh Exports",
            location: "Buenos Aires, AR",
            startYear: "2020",
            startMonth: "06",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Coordinate grower network and packhouse scheduling for EU-bound blueberries.\nImproved on-spec pack rates from 91% to 97%.\nBuilt weekly harvest forecasts shared with sales and freight.",
            bullets: true,
          },
          {
            title: "Field Agronomist",
            org: "Campo Verde Coop",
            location: "Córdoba, AR",
            startYear: "2017",
            startMonth: "02",
            endYear: "2020",
            endMonth: "05",
            endPresent: false,
            desc: "Advised member farms on irrigation and IPM programs. Supported certification readiness for GlobalG.A.P.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Cold-Chain Traceability Pilot",
            reference: "",
            referenceLink: false,
            year: "2024",
            desc: "Lot-level temperature and handling log from harvest to vessel for premium export customers.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Mateo Alvarez",
            role: "Pampa Fresh Exports / Commercial Director",
            phone: "+54 11 5555-0188",
            email: "mateo.alvarez@example.com",
          },
          {
            name: "Ana Ruiz",
            role: "Campo Verde Coop / Technical Manager",
            phone: "+54 351 555-0233",
            email: "ana.ruiz@example.com",
          },
        ],
      },
    },
    {
      id: "healthcare-clinical",
      label: "Healthcare / Clinical",
      photo: "samples/photos/healthcare-clinical.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Dr. Nadia<br />Hassan",
        title: "Clinical Operations Manager",
        phone: "501234567",
        phoneDial: "65",
        phoneCountry: "SG",
        email: "nadia.hassan@example.com",
        address: "12 Science Park Dr., Singapore 118225",
        linkedin: "nadiahassan-clinical",
        github: "",
        about:
          "Clinician-turned-operations manager focused on safe, efficient outpatient pathways. I translate clinical constraints into schedules, protocols, and staffing plans that patients and teams can trust.",
      },
      lists: {
        skills: [
          {
            name: "Clinical ops",
            skills: [
              "Care pathway design",
              "Clinic scheduling",
              "Quality improvement",
              "Protocol compliance",
              "Staffing models",
            ],
          },
          {
            name: "Clinical",
            skills: ["Outpatient medicine", "Patient safety", "EMR workflows"],
          },
        ],
        languages: ["English", "Malay", "Arabic"],
        education: [
          {
            title: "MBBS",
            org: "National University of Singapore",
            location: "Singapore",
            startYear: "2009",
            startMonth: "08",
            endYear: "2014",
            endMonth: "05",
            endPresent: false,
            desc: "Undergraduate medical degree with electives in internal medicine and health systems.",
          },
          {
            title: "M.P.H.",
            org: "NUS Saw Swee Hock School of Public Health",
            location: "Singapore",
            startYear: "2017",
            startMonth: "08",
            endYear: "2019",
            endMonth: "05",
            endPresent: false,
            desc: "Health services research and operations management coursework.",
          },
        ],
        experience: [
          {
            title: "Clinical Operations Manager",
            org: "Harbour Medical Centre",
            location: "Singapore",
            startYear: "2021",
            startMonth: "03",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Oversee outpatient operations for three specialty clinics.\nReduced average wait time by 17 minutes through slot redesign.\nLed incident review cadence with measurable follow-up actions.",
            bullets: true,
          },
          {
            title: "Resident Physician",
            org: "City General Hospital",
            location: "Singapore",
            startYear: "2015",
            startMonth: "01",
            endYear: "2021",
            endMonth: "02",
            endPresent: false,
            desc: "Internal medicine residency with rotations in acute care and ambulatory clinics. Mentored junior housestaff on documentation quality.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Ambulatory Flow Redesign",
            reference: "",
            referenceLink: false,
            year: "2023",
            desc: "Multidisciplinary project combining triage, rooming, and discharge checklist changes to improve throughput safely.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Dr. Wei Ling Tan",
            role: "Harbour Medical Centre / Medical Director",
            phone: "+65 6555 0191",
            email: "weiling.tan@example.com",
          },
          {
            name: "Dr. Aaron Goh",
            role: "City General Hospital / Program Director",
            phone: "+65 6555 0275",
            email: "aaron.goh@example.com",
          },
        ],
      },
    },
    {
      id: "psychology-counseling",
      label: "Psychology / Counseling",
      photo: "samples/photos/psychology-counseling.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Samira<br />Bloom",
        title: "Licensed Counseling Psychologist",
        phone: "412345678",
        phoneDial: "61",
        phoneCountry: "AU",
        email: "samira.bloom@example.com",
        address: "88 Oxford St., Paddington NSW 2021",
        linkedin: "samirabloom-psych",
        github: "",
        about:
          "Counseling psychologist providing evidence-based therapy for adults navigating anxiety, burnout, and life transitions. Warm, structured, and collaborative—grounded in CBT and ACT approaches.",
      },
      lists: {
        skills: [
          {
            name: "Clinical",
            skills: ["CBT", "ACT", "Trauma-informed care", "Assessment", "Group facilitation"],
          },
          {
            name: "Practice",
            skills: ["Case formulation", "Clinical notes", "Referral coordination", "Telehealth"],
          },
        ],
        languages: ["English", "Farsi"],
        education: [
          {
            title: "Master of Psychology (Clinical)",
            org: "University of Sydney",
            location: "Sydney, AU",
            startYear: "2016",
            startMonth: "02",
            endYear: "2018",
            endMonth: "11",
            endPresent: false,
            desc: "Clinical training with placements in community mental health and university counseling.",
          },
          {
            title: "B.Psych. (Hons)",
            org: "Macquarie University",
            location: "Sydney, AU",
            startYear: "2012",
            startMonth: "02",
            endYear: "2015",
            endMonth: "11",
            endPresent: false,
            desc: "Honours thesis on workplace burnout and coping styles.",
          },
        ],
        experience: [
          {
            title: "Licensed Counseling Psychologist",
            org: "Harbour Mind Clinic",
            location: "Sydney, AU",
            startYear: "2020",
            startMonth: "03",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Provide individual therapy for adults in private practice.\nFacilitate a weekly anxiety skills group.\nCollaborate with GPs on care plans and outcome monitoring.",
            bullets: true,
          },
          {
            title: "Provisional Psychologist",
            org: "Eastern Community Mental Health",
            location: "Sydney, AU",
            startYear: "2018",
            startMonth: "01",
            endYear: "2020",
            endMonth: "02",
            endPresent: false,
            desc: "Delivered short-term interventions and intake assessments under supervision in a public mental health setting.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Workplace Burnout Workshop Series",
            reference: "",
            referenceLink: false,
            year: "2024",
            desc: "Four-session psychoeducation series for professional services firms, with take-home worksheets and manager guidance notes.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Dr. Helen Marks",
            role: "Harbour Mind Clinic / Clinical Director",
            phone: "+61 2 5550 1188",
            email: "helen.marks@example.com",
          },
          {
            name: "James Crowley",
            role: "Eastern Community MH / Team Leader",
            phone: "+61 2 5550 2299",
            email: "james.crowley@example.com",
          },
        ],
      },
    },
    {
      id: "photography-videography",
      label: "Photography / Videography",
      photo: "samples/photos/photography-videography.jpg",
      contactVisibility: { ...VIS_NO_GITHUB },
      fields: {
        name: "Leo<br />Moreau",
        title: "Director of Photography",
        phone: "612345678",
        phoneDial: "33",
        phoneCountry: "FR",
        email: "leo.moreau@example.com",
        address: "18 Rue du Faubourg Saint-Antoine, 75012 Paris",
        linkedin: "leomoreau-dop",
        github: "",
        about:
          "Director of photography crafting grounded, character-led imagery for commercials and short films. Strong on lighting design, camera movement, and collaboration with directors and colorists.",
      },
      lists: {
        skills: [
          {
            name: "Image",
            skills: [
              "Cinematography",
              "Lighting design",
              "Camera operation",
              "Color collaboration",
              "Storyboarding",
            ],
          },
          {
            name: "Gear & tools",
            skills: ["ARRI Alexa", "Sony Venice", "DaVinci Resolve", "Premiere Pro", "Lightroom"],
          },
        ],
        languages: ["French", "English"],
        education: [
          {
            title: "Diplôme — Cinematography",
            org: "La Fémis",
            location: "Paris, FR",
            startYear: "2013",
            startMonth: "09",
            endYear: "2016",
            endMonth: "06",
            endPresent: false,
            desc: "Specialized in image and lighting. Thesis short explored night exteriors with minimal practicals.",
          },
        ],
        experience: [
          {
            title: "Director of Photography",
            org: "Studio Lumière",
            location: "Paris, FR",
            startYear: "2020",
            startMonth: "05",
            endYear: "",
            endMonth: "",
            endPresent: true,
            desc: "Lead DP for brand films and music videos.\nShot campaigns for fashion and hospitality clients across Europe.\nMentored camera trainees on set craft and safety.",
            bullets: true,
          },
          {
            title: "Camera Operator / Gaffer",
            org: "Freelance",
            location: "Paris / Lyon, FR",
            startYear: "2016",
            startMonth: "07",
            endYear: "2020",
            endMonth: "04",
            endPresent: false,
            desc: "Operated and lit commercial and documentary sets. Built a reputation for fast, clean setups on location.",
            bullets: false,
          },
        ],
        projects: [
          {
            title: "Still Waters — Short Film",
            reference: "vimeo.com/leomoreau/stillwaters",
            referenceLink: true,
            year: "2023",
            desc: "Narrative short lit entirely with practicals and bounce. Official selection at two regional festivals.",
            bullets: false,
          },
        ],
        references: [
          {
            name: "Camille Dubois",
            role: "Studio Lumière / Executive Producer",
            phone: "+33 1 55 55 01 40",
            email: "camille.dubois@example.com",
          },
          {
            name: "Marc Petit",
            role: "Independent / Director",
            phone: "+33 6 55 55 02 88",
            email: "marc.petit@example.com",
          },
        ],
      },
    },
  ];

  global.CV_CONTENT_SAMPLES = CV_CONTENT_SAMPLES;
})(typeof window !== "undefined" ? window : globalThis);
